### ISSUE TITLE
Make custom docker images triggers to relevant jobs

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-ci#1]
As an example, if the r2dbc/r2dbc-mssql docker image gets updated, it makes sense to build r2dbc-mssql. Same for postgres, etc. 

Additionally, triggering off 8-jdk docker image changes might not be bad either.

**Comment by nebhale** [comment]
I'm not too worried about this. Addition of Java 12, 13, etc. might be a case for testing, but 1.8.0_* hasn't proven to be problematic in the last five years.  The problems we've seen so far have all been around problems with Debian's version of Java and I'm willing to take that risk.
